# Generated by Django 4.2.1 on 2023-05-13 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MVT', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Insident',
            new_name='Incident',
        ),
    ]
