# Generated by Django 4.2.1 on 2023-05-16 23:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MVT', '0002_rename_insident_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incident',
            name='level',
            field=models.CharField(choices=[('Low', 'Bajo'), ('Mid', 'Medio'), ('MidHi', 'Alta'), ('Hi', 'Critico')], max_length=5),
        ),
    ]
