# Generated by Django 4.2.1 on 2023-05-16 23:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MVT', '0003_incident_date_alter_incident_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='date',
        ),
        migrations.AddField(
            model_name='incident',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
