# Generated by Django 4.2.1 on 2023-05-21 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MVT', '0004_remove_incident_date_incident_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=254)),
                ('image', models.ImageField(upload_to='imagen')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('IN', 'Incident'), ('RQ', 'Request')], max_length=2)),
                ('level', models.CharField(choices=[('Low', 'Bajo'), ('Mid', 'Medio'), ('MidHi', 'Alta'), ('Hi', 'Critico')], max_length=5)),
                ('url', models.URLField()),
                ('project', models.CharField(max_length=40)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Attach',
        ),
        migrations.DeleteModel(
            name='Incident',
        ),
        migrations.RenameModel(
            old_name='UserContact',
            new_name='UserIssue',
        ),
        migrations.AddField(
            model_name='incidentissue',
            name='user_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MVT.userissue'),
        ),
        migrations.AddField(
            model_name='attachissue',
            name='insident_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MVT.incidentissue'),
        ),
    ]
