# Generated by Django 4.2.1 on 2023-05-21 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MVT', '0005_attachissue_incidentissue_delete_attach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachissue',
            name='insident_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MVT.incidentissue'),
        ),
        migrations.AlterField(
            model_name='incidentissue',
            name='user_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MVT.userissue'),
        ),
    ]
